[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.135.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/author/daniel-souza/"
  to = "https://danielf-souza.github.io/"
  status = 301
  force = true

[[redirects]]
  from = "/author/stefano-baruffaldi/"
  to = "https://www.som.polimi.it/professor/baruffaldi-stefano/"
  status = 301
  force = true

[[redirects]]
  from = "/author/marco-guerzoni/"
  to = "https://www.unimib.it/marco-guerzoni"
  status = 301
  force = true

[[redirects]]
  from = "/author/gabriele-pellegrino/"
  to = "https://sites.google.com/view/gabrielepellegrino/home"
  status = 301
  force = true

[[redirects]]
  from = "/author/anita-quas/"
  to = "https://misom.unimi.it/profilo/anita-quas/"
  status = 301
  force = true

[[redirects]]
  from = "/author/felix-poege/"
  to = "https://www.felixpoege.eu/"
  status = 301
  force = true
